export const streetDictionary = {
  'Alexandra Lane': '1',
  'Allison Way': '3',
  'Andover Drive': '1',
  'Annes Court': '1',
  'Applewood Lane': '1',
  'Ashwell Avenue': '2',
  'Augusta Circle': '1',
  'Autumn Circle': '1',
  'Bailey Road': '3',
  'Barnyard Road': '2',
  'Barry Place': '3',
  'Basswood Court': '3',
  'Bayberry Lane': '3',
  'Beecher Lane': '1',
  'Bel-Air Circle': '2',
  'Belamose Avenue': '1',
  'Belden Lane': '2',
  'Bella Vista Drive': '1',
  'Berkshire Road': '3',
  'Birch Road': '2',
  'Blair Road': '1',
  'Blue Grass Court': '1',
  'Boulder Drive': '1',
  'Brandee Lane': '1',
  'Briarwood Court': '2',
  'Brimfield Way': '2',
  'Brook Street': '2',
  'Brookwood Drive': '2',
  'Bucks Crossing': '1',
  'Butternut Lane': '3',
  'Caliber Lane': '3',
  'Cambric Place': '1',
  'Cambridge Drive': '3',
  'Candle Lite Drive': '1',
  'Capitol Blvd': '2',
  'Carillon Drive': '2',
  'Carlton Lane': '1',
  'Carol Drive': '3',
  'Catherine Drive': '1',
  'Cedar Hollow': '2',
  'Chapin Avenue': '3',
  'Charter Road': '3',
  'Chatham Drive': '1',
  'Chestnut Court': '3',
  'Christiana Drive': '3',
  'Christopher Court': '1',
  'Church Street': '2',
  'Clearview Avenue': '1',
  'Clemens Court': '1',
  'Cobey Road': '1',
  'Cold Spring Road': '1',
  'Colonial Drive': '2',
  'Concord Drive': '3',
  'Copper Beech Drive': '1',
  'Corncrib Lane': '3',
  'Corporate Place': '2',
  'Country Club Court': '1',
  'Countryside Drive': '1',
  'Courtney Drive': '3',
  'Crestridge Road': '3',
  'Cricket Lane': '1',
  'Cromwell Avenue': '1',
  'Cronin Drive': '1',
  'Crystal Drive': '3',
  'Cumberland Place': '1',
  'Danforth Lane': '1',
  'Deer Path': '1',
  'Deerfield Run': '1',
  'Deming Road': '3',
  'Denyelle Drive': '1',
  'Dexter Road': '2',
  'Dividend Road': '2',
  'Dogwood Court.': '1',
  'Drum Hill Road': '2',
  'Drummond Drive': '1',
  'Dusty Lane': '1',
  'Eastview Terrace': '2',
  'Elizabeth Court': '1',
  'Elm Ridge Drive': '3',
  'Elm Street': '3',
  'Elm Street Extension': '1',
  'Esther Road': '2',
  'Evans Road': '2',
  'Evergreen Place': '3',
  'Falcon Ridge': '1',
  'Fallawater Court': '3',
  'Farms Village Road': '2',
  'Farmstead Road': '1',
  'Farview Drive': '1',
  'Fawn Run': '1',
  'Fern Street': '3',
  'Fernwood Drive': '1',
  'Fieldstone Drive': '1',
  'Footehill Road': '3',
  'Forest Street': '2',
  'Foxbriar Lane': '3',
  'Foxhill Drive': '1',
  'France Street': '1',
  'Friendly Way': '2',
  'Garden Street': '2',
  'Garfield Road': '1',
  'Gaylord Drive': '2',
  'George Road': '2',
  'Gilbert Avenue': '3',
  'Glastonbury Avenue': '2',
  'Goft Brook Lane': '2',
  'Gorman Road': '2',
  'Gray Fox Lane': '1',
  'Green View Drive': '1',
  'Grimes Road': '2',
  'Harbor View Drive': '2',
  'Haren Drive': '1',
  'Harvest Lane': '1',
  'Hawthorne Circle': '2',
  'Hayes Road': '1',
  'Heather Hill': '1',
  'Henry Street': '2',
  'Hickory Lane': '3',
  'Hidden Valley Drive': '1',
  'Highcrest Drive': '1',
  'Highland Street': '1',
  'Highmeadow Road': '3',
  'Highpoint Drive': '1',
  'Highview Drive': '2',
  'Hillside Avenue': '2',
  'Hollister Drive': '1',
  'Holly Hill Drive': '1',
  "Hunter's Ridge": '1',
  'Jason Drive': '1',
  "Jennifer's Way": '2',
  'Joiners Road': '2',
  'June Circle': '3',
  'Juniper Place': '3',
  'Kensington Lane': '2',
  'Kent Lane': '1',
  'Kingsley Court': '1',
  'Knoll Lane': '1',
  'Knollwood Road': '1',
  'Krol Farm Road': '1',
  'Lakeview Avenue': '1',
  'Lathrop Lane': '1',
  'Laura Lane': '2',
  'Laurel Road': '2',
  'Lavender Lane': '1',
  'Ledge Drive': '2',
  'Lexington Court': '3',
  'Lilola Road': '1',
  'Limner Circle': '1',
  'Litchfield Place': '3',
  'Little Oak Lane': '1',
  'Locust Circle': '2',
  'Lord Street': '2',
  'Louis Place': '2',
  'Lydia Drive': '1',
  'Main Street [2359-2518]': '2',
  'Main Street [2519-3408]': '2',
  'Maple Street': '1',
  'Mark Lane': '3',
  'Marshall Road': '2',
  'Martin Drive': '2',
  'Maryanna Way': '1',
  'Matteson Avenue': '2',
  'Maxwell Drive': '1',
  'Mclintosh Circle': '3',
  'Meadow Road': '2',
  'Meyers Drive': '2',
  'Michele Drive': '2',
  'Minnie Lane': '1',
  'Misty Crescent': '1',
  'Moser Drive': '2',
  'Mountain View Drive': '3',
  'Murphy Drive': '1',
  'Nessa Way': '2',
  'New Britain Avenue': '1',
  'New Road': '1',
  'North Condor Drive': '1',
  'Nutmeg Lane': '1',
  'Oak Hill Road': '2',
  'Old Dividend Road': '2',
  'Old Main Street': '2',
  'Old Tannery Lane': '1',
  'Old Windmill Crossing': '3',
  'Orchard Street': '3',
  'Oslund Way': '1',
  'Overlook Terrace': '1',
  'Parish Road': '1',
  'Park Drive': '1',
  'Parsonage Street [5-82]': '2',
  'Parsonage Street [120-438]': '3',
  'Partridge Drive': '3',
  'Pearl Lane': '2',
  'Pebblebrook Drive': '1',
  'Pelican Court': '1',
  'Penn Place': '1',
  'Pequot Drive': '1',
  'Peria Drive': '1',
  'Pheasant Drive': '3',
  'Pine Meadow': '1',
  'Pleasant Valley Road': '2',
  'Pondside Lane': '1',
  'Pratt Street': '2',
  'Quail Drive': '3',
  'Rachel Drive': '2',
  'Ramblewood Drive': '1',
  'Rangelight Road': '2',
  'Raymond Road': '3',
  'Red Fox Lane': '1',
  'Red Maple Circle': '1',
  'Redstone Circle': '1',
  'Rhodes Road': '1',
  'Richard Road': '3',
  'Ridge Road': '2',
  'Ridgewood Drive': '1',
  'Riverview Road': '2',
  'Robbins Lane': '2',
  'Robinson Road': '1',
  'Rocamora Road': '3',
  'Rose Court': '1',
  'Rosewood Drive': '1',
  'Sagamore Lane': '2',
  'Sage Road': '1',
  'Sandy Drive': '1',
  'Sawmill Road': '2',
  'School Street': '2',
  'Shea Circle': '3',
  'Siderake Road': '3',
  'Silas Deane Highway': '2',
  'Silo Drive': '3',
  'Sky View Drive': '1',
  'South Condor Drive': '1',
  'Southbrook Road': '2',
  'Speno Ridge': '1',
  'Springbrook Drive': '2',
  'Stagecoach Lane': '1',
  'Stanley Court': '2',
  'Starr Drive': '3',
  'Stepney Circle': '2',
  'Stevens Place': '1',
  'Stockton Lane': '1',
  'Stone Brook Crossing': '1',
  'Stonehill Drive': '1',
  'Stones Throw Court': '2',
  'Summer Lane': '1',
  'Summit Road': '2',
  'Sunny Crest Drive': '2',
  'Sunset Ridge': '1',
  'Sutton Road': '2',
  'Tall Pine Lane': '1',
  'Tedwin Farms Road': '1',
  'Ten Rod Highway': '1',
  'Terry Lane': '3',
  'Textbook Avenue': '3',
  'The Arbors': '1',
  'The Mews': '1',
  'Thomas Court': '1',
  'Tollgate Road': '2',
  'Trinity Ridge': '1',
  'Truman Way': '3',
  'Tumblebrook Road': '3',
  'Valley Brook Road': '3',
  'Valley Crest Drive': '3',
  'Valley View Drive': '3',
  'Vexation Hill Drive': '1',
  'Walnut Road': '2',
  'Washington Street': '2',
  'Waterchase Drive': '2',
  'Watercourse Row': '1',
  'Waters Avenue': '3',
  'Webber Road': '2',
  'Webster Lane': '3',
  'Wells Road': '2',
  'West Ridge Dr.': '1',
  'West Street': '2',
  'Westbrook Road': '2',
  'Westerly Terrace': '1',
  'Westmeadow Road': '1',
  'Whitewood Drive': '1',
  'Wildwood Lane': '1',
  'Willow Road': '2',
  'Windy Hill Lane': '1',
  'Winesap Circle': '3',
  'Winters Lane': '1',
  'Woodfield Crossing': '1',
  'Woodhaven Road': '1',
  'Woodland Road': '2',
  'Wright Road': '3',
  'Wynding Brook Drive': '1'
}
